### ISSUE TITLE
Newton-Raphson failed to converge within 10000 iterations.

### ISSUE THREAD

**Issue by calrey** [RayDeCampo/java-xirr#16]
double xirr = new org.decampo.xirr.Xirr(Arrays.asList(
            new Transaction(-1750000.00, "2017-01-06"),
            new Transaction(-2500000.00, "2017-01-06"),
            new Transaction(-5625000000.00, "2017-01-09"),
            new Transaction(-1000000.00, "2017-01-18"),
            new Transaction(228159246.58, "2017-11-20"),
            new Transaction(119665.77, "2017-12-22"),
            new Transaction(170951.11, "2017-12-22"),
            new Transaction(-1750000.00, "2018-01-08"),
            new Transaction(281250000.00, "2019-01-30"),
            new Transaction(680010.61, "2019-03-12"),
            new Transaction(952014.86, "2019-03-12"),
            new Transaction(355381.27, "2019-11-20"),
            new Transaction(281250000.00, "2019-11-20"),
            **_new Transaction(497533.00, "2019-11-20"),_**
            new Transaction(15667873.77, "2020-03-31")
        )).xirr();

Exception in thread "main" org.decampo.xirr.NonconvergenceException: Newton-Raphson failed to converge within 10000 iterations.
	at org.decampo.xirr.NewtonRaphson$Calculation.solve(NewtonRaphson.java:216)
	at org.decampo.xirr.NewtonRaphson.inverse(NewtonRaphson.java:89)
	at org.decampo.xirr.NewtonRaphson.findRoot(NewtonRaphson.java:70)
	at org.decampo.xirr.NewtonRaphson$Builder.findRoot(NewtonRaphson.java:136)
	at org.decampo.xirr.Xirr.xirr(Xirr.java:155)
	at test.IRRTest.main(IRRTest.java:58)

Run throws the exception， Change to 50000 iterations and still throw this exception.

When I change the bold part to **_new Transaction(497532.99, "2019-11-20"),_**, the calculation is successful.

When the bold part is changed to **_new Transaction(497533.00, "2019-11-21"),_**, the calculation is also successful.

**Comment by calrey** [comment]
double xirr = Xirr.builder().withNewtonRaphsonBuilder(NewtonRaphson.builder()
                .withIterations(10000)
                **_.withTolerance(0.000001))_**
                .withGuess(0.1)
                .withTransactions(
                        new Transaction(-1750000.00, "2017-01-06"),
                        new Transaction(-2500000.00, "2017-01-06"),
                        new Transaction(-5625000000.00, "2017-01-09"),
                        new Transaction(-1000000.00, "2017-01-18"),
                        new Transaction(228159246.58, "2017-11-20"),
                        new Transaction(119665.77, "2017-12-22"),
                        new Transaction(170951.11, "2017-12-22"),
                        new Transaction(-1750000.00, "2018-01-08"),
                        new Transaction(281250000.00, "2019-01-30"),
                        new Transaction(680010.61, "2019-03-12"),
                        new Transaction(952014.86, "2019-03-12"),
                        new Transaction(355381.27, "2019-11-20"),
                        new Transaction(281250000.00, "2019-11-20"),
                        new Transaction(497533.00, "2019-11-20"),
                        new Transaction(15667873.77, "2020-03-31")
                ).xirr();

I modified the tolerance value, and the calculation was successful ！
